### ISSUE TITLE
Add theme

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Scholarships-STEM#9]
I have added a [theme](https://github.com/tapaswenipathak/Theme).

- Install using `npm i list-theme`.
- Add the information present in [index.html](https://github.com/tapaswenipathak/Scholarships-STEM/blob/master/index.html) in the theme's [index.html](https://github.com/tapaswenipathak/Theme/blob/master/index.html#L6-L42) 
- Deploy on a Heroku App.
- Create a PR, add the deployed heroku app link.
- Take the credentials from me.
- Deploy in my Heroku account.

Dep #7, #8 .

**Comment by singalhimanshu** [comment]
I am working on it.

**Comment by singalhimanshu** [comment]
It shows list-theme is not in the npm registry error 404.

**Comment by tapaswenipathak** [comment]
Can you resolve using [this](https://github.com/tapaswenipathak/Research-Paper-Publications/issues/11#issuecomment-489734991)?

**Comment by singalhimanshu** [comment]
So I just put the whole theme repository into it without doing the install?

**Comment by tapaswenipathak** [comment]
You should put the code and then integrate the theme. I created a ticket the error is as the package.json is missing few fields, I will do in the evening.

**Comment by anuragsarkar** [comment]
Do I need update the [theme](https://opensourceinternships.herokuapp.com) or fix the css issue ?

**Comment by tapaswenipathak** [comment]
On Thu, May 16, 2019 at 4:43 PM Anurag Sarkar <notifications@github.com> wrote:
>
> Do I need update the theme or fix the css issue ?

Please update the theme repository.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
